# SPDX-FileCopyrightText: 2025 Joe Pitt
#
# SPDX-License-Identifier: GPL-3.0-only

---
name: Get Latest Version from DockerHub Image Tags
author: Joe Pitt
description: Get the latest semantic version number from a Docker Hub repository's tagged images.
inputs:
  dockerhub_username:
    description: The user to authenticate to the Docker Hub API as.
    required: true
  dockerhub_token:
    description: The token to authenticate to the Docker Hub API with (must have read access).
    required: true
  namespace:
    description: The namespace the repository is in. Defaults to "library".
    required: false
    default: library
  repository:
    description: The repository to search tags for.
    required: true
  greater_equal_version:
    description: The minimum version to accept, e.g. 2.0.0. Defaults to None.
    required: false
  less_than_version:
    description: The version to accept versions less than, e.g. 3.0.0. Defaults to None.
    required: false
outputs:
  tag:
    description: The image tag for the latest version.
    value: ${{ steps.get_version.outputs.tag }}
  version:
    description: The latest version number.
    value: ${{ steps.get_version.outputs.version }}
runs:
  using: composite
  steps:
  - name: Get Latest Version
    id: get_version
    env:
      GITHUB_ACTION_PATH: ${{ github.action_path }}
      INPUT_dockerhub_token: ${{ inputs.dockerhub_token }}
      INPUT_dockerhub_username: ${{ inputs.dockerhub_username }}
      INPUT_greater_equal_version: ${{ inputs.greater_equal_version }}
      INPUT_less_than_version: ${{ inputs.less_than_version }}
      INPUT_namespace: ${{ inputs.namespace }}
      INPUT_repository: ${{ inputs.repository }}
    shell: python
    run: |
      from os import getenv
      from os.path import abspath, join
      import sys

      sys.path.insert(1, abspath(join(getenv("GITHUB_ACTION_PATH", "."), "lib")))

      from get_latest_version.dockerhub import get_latest_image_version
      from get_latest_version.functions import clean_version
      from semver import Version

      greater_equal_version = None
      if getenv("INPUT_greater_equal_version") is not None and len(getenv("INPUT_greater_equal_version")) >= 5:
          greater_equal_version = Version.parse(getenv("INPUT_greater_equal_version"))
      less_than_version = None
      if getenv("INPUT_less_than_version") is not None and len(getenv("INPUT_less_than_version")) >= 5:
          less_than_version = Version.parse(getenv("INPUT_less_than_version"))

      tag = get_latest_image_version(
          username=getenv("INPUT_dockerhub_username"),
          token=getenv("INPUT_dockerhub_token"),
          namespace=getenv("INPUT_namespace"),
          repository=getenv("INPUT_repository"),
          greater_equal_version=greater_equal_version,
          less_than_version=less_than_version,
      )

      with open(getenv("GITHUB_OUTPUT"), "a", encoding="utf-8") as f:
          f.write(f"tag={tag}\n")
          f.write(f"version={Version.parse(clean_version(tag))}\n")
  - name: Print Version
    id: print
    run: |
      echo "Latest version ${{ steps.get_version.outputs.version }} tagged as docker.io/${{ inputs.namespace }}/${{ inputs.repository }}:${{ steps.get_version.outputs.tag }}"
    shell: bash
branding:
  color: blue
  icon: disc